const actionTypes = {
  GET_PLAYER_LIST: 'GET_PLAYER_LIST',
  SET_PLAYER_LIST: 'SET_PLAYER_LIST',
  UPDATE_PLAYER: 'UPDATE_PLAYER',
  UPDATE_GAME: 'UPDATE_GAME',
  SET_ERROR: 'SET_ERROR',
  START_GAME: 'START_GAME'
};

export default actionTypes;
