const actionTypes = {
  CREATE_GAME_AND_PLAYER: 'CREATE_GAME_AND_PLAYER',
  CREATE_GAME: 'CREATE_GAME',
  CREATE_GAME_SUCCESS: 'CREATE_GAME_SUCCESS',
  CREATE_PLAYER: 'CREATE_PLAYER',
  FIND_GAME: 'FIND_GAME',
  JOIN_GAME: 'JOIN_GAME',
  SET_GAME: 'SET_GAME',
  SET_PLAYER: 'SET_PLAYER',
  SET_ERROR: 'SET_ERROR'
};

export default actionTypes;
